#spring
spring:
  data:
    #mongodb
    mongodb:
      uri: mongodb://127.0.0.1:27017/test
      
  #i18n
  messages:
    basename: i18n/messages
    
  #thymeleaf
  thymeleaf:
    check-template: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    
  #datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iotx?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    
  #hibernate
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
    
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 20
      max-wait: 60000
      max-idle: 20
      min-idle: 1
    database: 0

  #kafka
  kafka:
    bootstrap-servers:
    - 10.2.1.223:9092
    consumer:
      group-id: myGroup
    template:
      default-topic: testSensor
    listener:
      concurrency: 3
    producer:
      batch-size: 1000

  #mail
  mail:
    host: smtp.qq.com
    username: 573380618@qq.com
    password: wjberetzvinnbdji
    properties:
      mail:
        smtp:
          #如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的。
          auth: true
          # STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
          starttls:
            enable: true
            
  # freemarker
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path:
    - classpath:/templates/
